var annotated_dup =
[
    [ "bio_addr_t", "structbio__addr__t.html", "structbio__addr__t" ],
    [ "bio_allocator_t", "structbio__allocator__t.html", "structbio__allocator__t" ],
    [ "bio_cls_entry_t", "structbio__cls__entry__t.html", null ],
    [ "bio_cls_t", "structbio__cls__t.html", "structbio__cls__t" ],
    [ "bio_coro_impl_s", "structbio__coro__impl__s.html", null ],
    [ "bio_coro_t", "structbio__coro__t.html", null ],
    [ "bio_ctx_t", "structbio__ctx__t.html", null ],
    [ "bio_error_t", "structbio__error__t.html", "structbio__error__t" ],
    [ "bio_file_logger_options_t", "structbio__file__logger__options__t.html", "structbio__file__logger__options__t" ],
    [ "bio_file_t", "structbio__file__t.html", null ],
    [ "bio_fmt_buf_t", "structbio__fmt__buf__t.html", null ],
    [ "bio_freebsd_options_t", "structbio__freebsd__options__t.html", "structbio__freebsd__options__t" ],
    [ "bio_handle_slot_t", "structbio__handle__slot__t.html", null ],
    [ "bio_handle_t", "structbio__handle__t.html", "structbio__handle__t" ],
    [ "bio_linux_options_t", "structbio__linux__options__t.html", "structbio__linux__options__t" ],
    [ "bio_log_ctx_t", "structbio__log__ctx__t.html", "structbio__log__ctx__t" ],
    [ "bio_log_options_t", "structbio__log__options__t.html", "structbio__log__options__t" ],
    [ "bio_logger_t", "structbio__logger__t.html", null ],
    [ "bio_monitor_impl_t", "structbio__monitor__impl__t.html", null ],
    [ "bio_monitor_t", "structbio__monitor__t.html", null ],
    [ "bio_options_t", "structbio__options__t.html", "structbio__options__t" ],
    [ "bio_service_msg_base_t", "structbio__service__msg__base__t.html", null ],
    [ "bio_signal_impl_t", "structbio__signal__impl__t.html", null ],
    [ "bio_signal_t", "structbio__signal__t.html", null ],
    [ "bio_socket_t", "structbio__socket__t.html", null ],
    [ "bio_stat_t", "structbio__stat__t.html", "structbio__stat__t" ],
    [ "bio_tag_t", "structbio__tag__t.html", "structbio__tag__t" ],
    [ "bio_timer_entry_t", "structbio__timer__entry__t.html", null ],
    [ "bio_timer_t", "structbio__timer__t.html", null ],
    [ "bio_windows_options_t", "structbio__windows__options__t.html", "structbio__windows__options__t" ]
];