#!/bin/sh -e

./build || true

inotifywait -r -e CLOSE_WRITE -m include src tests samples Doxyfile doc-index.md | \
    while read path action file
	do
		printf '%*s\n' "$(tput cols)" '' | tr ' ' -
		doxygen
		if ./build
		then
			bin/Debug/tests || true
		fi
    done
